development:
  adapter: postgresql
  encoding: unicode
  database: soma_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: soma_test
  pool: 5
  username: ryan
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: soma_production
  pool: 5
  username: ryan
  password: MonkeyB@nanaSwimmingP00Ls
