development:
  bucket: soma_ogg_development
  access_key_id: AKIAJTTWXS4V7XVFJN6Q
  secret_access_key: <%= ENV['GODDAMNYOURYAN_S3_SECRET_ACCESS_KEY'] %>

test:
  bucket: myapptest
  access_key_id: AKIAJTTWXS4V7XVFJN6Q
  secret_access_key: <%= ENV['GODDAMNYOURYAN_S3_SECRET_ACCESS_KEY'] %>

production:
  bucket: soma_ogg_production
  access_key_id: AKIAJTTWXS4V7XVFJN6Q
  secret_access_key: <%= ENV['GODDAMNYOURYAN_S3_SECRET_ACCESS_KEY'] %>
