development:
  bucket: soma_thumb_development
  access_key_id: AKIAJ2VXOJBAKFYA6H4Q
  secret_access_key: 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

test:
  bucket: myapptest
  access_key_id: AKIAJ2VXOJBAKFYA6H4Q
  secret_access_key: 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

production:
  bucket: soma_thumb_production
  access_key_id: AKIAJ2VXOJBAKFYA6H4Q
  secret_access_key: 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